name: vehicle-service

on:
  pull_request:
    paths:
      - "vehicle-service/**"
      - ".github/workflows/vehicle-service.yml"
      - ".github/workflows/reusable-*.yml"
  push:
    branches: [main]
    paths:
      - "vehicle-service/**"
      - ".github/workflows/vehicle-service.yml"
      - ".github/workflows/reusable-*.yml"

## For this specific service and this specific Git reference (branch/PR/tag),
## allow only one workflow execution at a time; if a newer one starts, cancel the older one
concurrency:
  group: vehicle-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/reusable-ci.yml
    with:
      service: vehicle-service

  cd:
    if: github.ref == 'refs/heads/main'
    needs: ci
    uses: ./.github/workflows/reusable-cd.yml
    with:
      service: vehicle-service
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}